---
- hosts: localhost
  gather_facts: false
  vars:
    tower_host: "{{ lookup('ENV', 'TOWER_HOST') }}"
    tower_username: "{{ lookup('ENV', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('ENV', 'TOWER_PASSWORD') }}"
  collections:
    - ansible_tower.tower_modules
  tasks:
    - name: "Include tests for tower module {{ item }}"
      include_tasks: "tower_{{ item }}/tasks/main.yml"
      loop:
        - common
        - credential
        - credential_type
        - group
        - host
        - inventory
        - inventory_source
        - job_cancel
        - job_launch
        - job_list
        - job_template
        - job_wait
        - label
        - notification
        - organization
        - project
        - receive
        - role
        - send
        - settings
        - team
        - user
        - workflow_launch
        - workflow_template
