---
- hosts: localhost
  gather_facts: false
  vars:
    tower_host: "{{ lookup('ENV', 'TOWER_HOST') }}"
    tower_username: "{{ lookup('ENV', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('ENV', 'TOWER_PASSWORD') }}"
  collections:
    - chrismeyersfsu.tower_modules
  tasks:
    - name: "Invoke tests for tower module {{ tower_module_under_test }}"
      include_tasks: "tower_{{ tower_module_under_test }}/tasks/main.yml"
